package org.datanucleus;

import java.io.Serializable;
import org.datanucleus.enhancement.Persistable;
import org.datanucleus.enhancement.StateManager;

public class ClassNameConstants {
   public static final String Object = Object.class.getName();
   public static final String Serializable = Serializable.class.getName();
   public static final String BOOLEAN;
   public static final String BYTE;
   public static final String CHAR;
   public static final String DOUBLE;
   public static final String FLOAT;
   public static final String INT;
   public static final String LONG;
   public static final String SHORT;
   public static final String JAVA_LANG_BOOLEAN;
   public static final String JAVA_LANG_BYTE;
   public static final String JAVA_LANG_CHARACTER;
   public static final String JAVA_LANG_DOUBLE;
   public static final String JAVA_LANG_FLOAT;
   public static final String JAVA_LANG_INTEGER;
   public static final String JAVA_LANG_LONG;
   public static final String JAVA_LANG_SHORT;
   public static final String JAVA_LANG_STRING;
   public static final String JAVA_MATH_BIGDECIMAL;
   public static final String JAVA_MATH_BIGINTEGER;
   public static final String JAVA_SQL_DATE;
   public static final String JAVA_SQL_TIME;
   public static final String JAVA_SQL_TIMESTAMP;
   public static final String JAVA_UTIL_DATE;
   public static final String JAVA_IO_SERIALIZABLE;
   public static final String BOOLEAN_ARRAY;
   public static final String BYTE_ARRAY;
   public static final String CHAR_ARRAY;
   public static final String DOUBLE_ARRAY;
   public static final String FLOAT_ARRAY;
   public static final String INT_ARRAY;
   public static final String LONG_ARRAY;
   public static final String SHORT_ARRAY;
   public static final String JAVA_LANG_BOOLEAN_ARRAY;
   public static final String JAVA_LANG_BYTE_ARRAY;
   public static final String JAVA_LANG_CHARACTER_ARRAY;
   public static final String JAVA_LANG_DOUBLE_ARRAY;
   public static final String JAVA_LANG_FLOAT_ARRAY;
   public static final String JAVA_LANG_INTEGER_ARRAY;
   public static final String JAVA_LANG_LONG_ARRAY;
   public static final String JAVA_LANG_SHORT_ARRAY;
   public static final String IDENTITY_SINGLEFIELD_LONG;
   public static final String IDENTITY_SINGLEFIELD_INT;
   public static final String IDENTITY_SINGLEFIELD_STRING;
   public static final String IDENTITY_SINGLEFIELD_CHAR;
   public static final String IDENTITY_SINGLEFIELD_BYTE;
   public static final String IDENTITY_SINGLEFIELD_OBJECT;
   public static final String IDENTITY_SINGLEFIELD_SHORT;
   public static final String IDENTITY_OID_IMPL;
   public static final String PERSISTABLE;
   public static final String STATE_MANAGER;

   static {
      BOOLEAN = ClassConstants.BOOLEAN.getName();
      BYTE = ClassConstants.BYTE.getName();
      CHAR = ClassConstants.CHAR.getName();
      DOUBLE = ClassConstants.DOUBLE.getName();
      FLOAT = ClassConstants.FLOAT.getName();
      INT = ClassConstants.INT.getName();
      LONG = ClassConstants.LONG.getName();
      SHORT = ClassConstants.SHORT.getName();
      JAVA_LANG_BOOLEAN = ClassConstants.JAVA_LANG_BOOLEAN.getName();
      JAVA_LANG_BYTE = ClassConstants.JAVA_LANG_BYTE.getName();
      JAVA_LANG_CHARACTER = ClassConstants.JAVA_LANG_CHARACTER.getName();
      JAVA_LANG_DOUBLE = ClassConstants.JAVA_LANG_DOUBLE.getName();
      JAVA_LANG_FLOAT = ClassConstants.JAVA_LANG_FLOAT.getName();
      JAVA_LANG_INTEGER = ClassConstants.JAVA_LANG_INTEGER.getName();
      JAVA_LANG_LONG = ClassConstants.JAVA_LANG_LONG.getName();
      JAVA_LANG_SHORT = ClassConstants.JAVA_LANG_SHORT.getName();
      JAVA_LANG_STRING = ClassConstants.JAVA_LANG_STRING.getName();
      JAVA_MATH_BIGDECIMAL = ClassConstants.JAVA_MATH_BIGDECIMAL.getName();
      JAVA_MATH_BIGINTEGER = ClassConstants.JAVA_MATH_BIGINTEGER.getName();
      JAVA_SQL_DATE = ClassConstants.JAVA_SQL_DATE.getName();
      JAVA_SQL_TIME = ClassConstants.JAVA_SQL_TIME.getName();
      JAVA_SQL_TIMESTAMP = ClassConstants.JAVA_SQL_TIMESTAMP.getName();
      JAVA_UTIL_DATE = ClassConstants.JAVA_UTIL_DATE.getName();
      JAVA_IO_SERIALIZABLE = ClassConstants.JAVA_IO_SERIALIZABLE.getName();
      BOOLEAN_ARRAY = boolean[].class.getName();
      BYTE_ARRAY = byte[].class.getName();
      CHAR_ARRAY = char[].class.getName();
      DOUBLE_ARRAY = double[].class.getName();
      FLOAT_ARRAY = float[].class.getName();
      INT_ARRAY = int[].class.getName();
      LONG_ARRAY = long[].class.getName();
      SHORT_ARRAY = short[].class.getName();
      JAVA_LANG_BOOLEAN_ARRAY = Boolean[].class.getName();
      JAVA_LANG_BYTE_ARRAY = Byte[].class.getName();
      JAVA_LANG_CHARACTER_ARRAY = Character[].class.getName();
      JAVA_LANG_DOUBLE_ARRAY = Double[].class.getName();
      JAVA_LANG_FLOAT_ARRAY = Float[].class.getName();
      JAVA_LANG_INTEGER_ARRAY = Integer[].class.getName();
      JAVA_LANG_LONG_ARRAY = Long[].class.getName();
      JAVA_LANG_SHORT_ARRAY = Short[].class.getName();
      IDENTITY_SINGLEFIELD_LONG = ClassConstants.IDENTITY_SINGLEFIELD_LONG.getName();
      IDENTITY_SINGLEFIELD_INT = ClassConstants.IDENTITY_SINGLEFIELD_INT.getName();
      IDENTITY_SINGLEFIELD_STRING = ClassConstants.IDENTITY_SINGLEFIELD_STRING.getName();
      IDENTITY_SINGLEFIELD_CHAR = ClassConstants.IDENTITY_SINGLEFIELD_CHAR.getName();
      IDENTITY_SINGLEFIELD_BYTE = ClassConstants.IDENTITY_SINGLEFIELD_BYTE.getName();
      IDENTITY_SINGLEFIELD_OBJECT = ClassConstants.IDENTITY_SINGLEFIELD_OBJECT.getName();
      IDENTITY_SINGLEFIELD_SHORT = ClassConstants.IDENTITY_SINGLEFIELD_SHORT.getName();
      IDENTITY_OID_IMPL = ClassConstants.IDENTITY_DATASTORE_IMPL.getName();
      PERSISTABLE = Persistable.class.getName();
      STATE_MANAGER = StateManager.class.getName();
   }
}
