package org.datanucleus;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import org.datanucleus.enhancement.ExecutionContextReference;
import org.datanucleus.enhancement.Persistable;
import org.datanucleus.enhancement.StateManager;
import org.datanucleus.identity.ByteId;
import org.datanucleus.identity.CharId;
import org.datanucleus.identity.DatastoreIdImpl;
import org.datanucleus.identity.IntId;
import org.datanucleus.identity.LongId;
import org.datanucleus.identity.ObjectId;
import org.datanucleus.identity.ShortId;
import org.datanucleus.identity.StringId;
import org.datanucleus.metadata.MetaDataManager;
import org.datanucleus.store.StoreManager;

public class ClassConstants {
   public static final ClassLoader NUCLEUS_CONTEXT_LOADER = NucleusContext.class.getClassLoader();
   public static final Class BOOLEAN;
   public static final Class BYTE;
   public static final Class CHAR;
   public static final Class DOUBLE;
   public static final Class FLOAT;
   public static final Class INT;
   public static final Class LONG;
   public static final Class SHORT;
   public static final Class JAVA_LANG_BOOLEAN;
   public static final Class JAVA_LANG_BYTE;
   public static final Class JAVA_LANG_CHARACTER;
   public static final Class JAVA_LANG_DOUBLE;
   public static final Class JAVA_LANG_FLOAT;
   public static final Class JAVA_LANG_INTEGER;
   public static final Class JAVA_LANG_LONG;
   public static final Class JAVA_LANG_SHORT;
   public static final Class JAVA_LANG_STRING;
   public static final Class JAVA_MATH_BIGDECIMAL;
   public static final Class JAVA_MATH_BIGINTEGER;
   public static final Class JAVA_SQL_DATE;
   public static final Class JAVA_SQL_TIME;
   public static final Class JAVA_SQL_TIMESTAMP;
   public static final Class JAVA_UTIL_DATE;
   public static final Class JAVA_IO_SERIALIZABLE;
   public static final Class PERSISTENCE_NUCLEUS_CONTEXT;
   public static final Class NUCLEUS_CONTEXT;
   public static final Class CLASS_LOADER_RESOLVER;
   public static final Class STORE_MANAGER;
   public static final Class METADATA_MANAGER;
   public static final Class EXECUTION_CONTEXT;
   public static final Class EXECUTION_CONTEXT_REFERENCE;
   public static final Class PERSISTABLE;
   public static final Class STATE_MANAGER;
   public static final Class IDENTITY_SINGLEFIELD_LONG;
   public static final Class IDENTITY_SINGLEFIELD_INT;
   public static final Class IDENTITY_SINGLEFIELD_STRING;
   public static final Class IDENTITY_SINGLEFIELD_CHAR;
   public static final Class IDENTITY_SINGLEFIELD_BYTE;
   public static final Class IDENTITY_SINGLEFIELD_OBJECT;
   public static final Class IDENTITY_SINGLEFIELD_SHORT;
   public static final Class IDENTITY_DATASTORE_IMPL;

   static {
      BOOLEAN = Boolean.TYPE;
      BYTE = Byte.TYPE;
      CHAR = Character.TYPE;
      DOUBLE = Double.TYPE;
      FLOAT = Float.TYPE;
      INT = Integer.TYPE;
      LONG = Long.TYPE;
      SHORT = Short.TYPE;
      JAVA_LANG_BOOLEAN = Boolean.class;
      JAVA_LANG_BYTE = Byte.class;
      JAVA_LANG_CHARACTER = Character.class;
      JAVA_LANG_DOUBLE = Double.class;
      JAVA_LANG_FLOAT = Float.class;
      JAVA_LANG_INTEGER = Integer.class;
      JAVA_LANG_LONG = Long.class;
      JAVA_LANG_SHORT = Short.class;
      JAVA_LANG_STRING = String.class;
      JAVA_MATH_BIGDECIMAL = BigDecimal.class;
      JAVA_MATH_BIGINTEGER = BigInteger.class;
      JAVA_SQL_DATE = Date.class;
      JAVA_SQL_TIME = Time.class;
      JAVA_SQL_TIMESTAMP = Timestamp.class;
      JAVA_UTIL_DATE = java.util.Date.class;
      JAVA_IO_SERIALIZABLE = Serializable.class;
      PERSISTENCE_NUCLEUS_CONTEXT = PersistenceNucleusContext.class;
      NUCLEUS_CONTEXT = NucleusContext.class;
      CLASS_LOADER_RESOLVER = ClassLoaderResolver.class;
      STORE_MANAGER = StoreManager.class;
      METADATA_MANAGER = MetaDataManager.class;
      EXECUTION_CONTEXT = ExecutionContext.class;
      EXECUTION_CONTEXT_REFERENCE = ExecutionContextReference.class;
      PERSISTABLE = Persistable.class;
      STATE_MANAGER = StateManager.class;
      IDENTITY_SINGLEFIELD_LONG = LongId.class;
      IDENTITY_SINGLEFIELD_INT = IntId.class;
      IDENTITY_SINGLEFIELD_STRING = StringId.class;
      IDENTITY_SINGLEFIELD_CHAR = CharId.class;
      IDENTITY_SINGLEFIELD_BYTE = ByteId.class;
      IDENTITY_SINGLEFIELD_OBJECT = ObjectId.class;
      IDENTITY_SINGLEFIELD_SHORT = ShortId.class;
      IDENTITY_DATASTORE_IMPL = DatastoreIdImpl.class;
   }
}
