package org.codehaus.janino;

public enum TokenType {
   END_OF_INPUT,
   IDENTIFIER,
   KEYWORD,
   INTEGER_LITERAL,
   FLOATING_POINT_LITERAL,
   BOOLEAN_LITERAL,
   CHARACTER_LITERAL,
   STRING_LITERAL,
   NULL_LITERAL,
   OPERATOR,
   WHITE_SPACE,
   C_PLUS_PLUS_STYLE_COMMENT,
   C_STYLE_COMMENT;

   // $FF: synthetic method
   private static TokenType[] $values() {
      return new TokenType[]{END_OF_INPUT, IDENTIFIER, KEYWORD, INTEGER_LITERAL, FLOATING_POINT_LITERAL, BOOLEAN_LITERAL, CHARACTER_LITERAL, STRING_LITERAL, NULL_LITERAL, OPERATOR, WHITE_SPACE, C_PLUS_PLUS_STYLE_COMMENT, C_STYLE_COMMENT};
   }
}
